// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flvfasxlrumtsaavnyvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsdmZhc3hscnVtdHNhYXZueXZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTY1NTcsImV4cCI6MjA3MTA5MjU1N30.RlbTSNOo04ehHCbwwP2Bc8tRlO-SiQeaa28AiUz6u0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});